spring:
  config:
    import:
      - application.yml

  datasource:
    url: jdbc:h2:mem:test_db
    username: sa
    password:
    driver-class-name: org.h2.Driver

logging:
  file:
    name: logs/test.log
  level:
    "[com.mak]": TRACE
