spring:
  config:
    import:
      - application.yml

  datasource:
    url: jdbc:mysql://localhost:3306/temp
    username: temp
    password: temp
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  file:
    name: logs/dev.log
  level:
    "[com.mak]": DEBUG
